- hosts: all
  become: true
  tasks:
    - name: Apply Kubernetes deployment from target node
      command: kubectl apply -f /home/ubuntu/Deployment.yml

    - name: Apply Kubernetes service from target node
      command: kubectl apply -f /home/ubuntu/Service.yml
