- hosts: all
  become: true
  vars:
    aws_region: "ap-south-1"
    aws_access_key_id: "{{ lookup('ini', 'default.aws_access_key_id file=/home/ubuntu/.aws/credentials') }}"
    aws_secret_access_key: "{{ lookup('ini', 'default.aws_secret_access_key file=/home/ubuntu/.aws/credentials') }}"

  tasks:
    - name: Delete old deployment
      command: kubectl delete -f /home/ubuntu/Deployment.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        AWS_DEFAULT_REGION: "{{ aws_region }}"
      ignore_errors: yes

    - name: Delete old service
      command: kubectl delete -f /home/ubuntu/Service.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        AWS_DEFAULT_REGION: "{{ aws_region }}"
      ignore_errors: yes

    - name: Apply deployment
      command: kubectl apply -f /home/ubuntu/Deployment.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        AWS_DEFAULT_REGION: "{{ aws_region }}"

    - name: Apply service
      command: kubectl apply -f /home/ubuntu/Service.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        AWS_DEFAULT_REGION: "{{ aws_region }}"
