- hosts: all
  become: true
  tasks:
<<<<<<< HEAD
    - name: create new deployment
      command: kubectl apply -f /home/ubuntu/Deployment.yml
    - name: create new service
      command: kubectl apply -f /home/ubuntu/Service.yml
=======
    - name: Copy deployment file to control node (optional if already there)
      copy:
        src: ./deployment.yml
        dest: /home/ubuntu/deployment.yml
      delegate_to: 127.0.0.1

    - name: Copy service file to control node (optional if already there)
      copy:
        src: ./Service.yml
        dest: /home/ubuntu/Service.yml
      delegate_to: 127.0.0.1

    - name: Apply Kubernetes deployment from control node
      command: kubectl apply -f /home/ubuntu/deployment.yml
      delegate_to: 127.0.0.1

    - name: Apply Kubernetes service from control node
      command: kubectl apply -f /home/ubuntu/Service.yml
      delegate_to: 127.0.0.1
>>>>>>> 6a34ae5 (Files added changes in ansible.yml)
