---
- hosts: all
  become: false
  vars:
    kubeconfig_path: /home/ubuntu/.kube/config
    aws_region: ap-south-1
  tasks:
    - name: Check AWS identity on remote
      shell: aws sts get-caller-identity
      register: aws_identity
    - debug:
        msg: "AWS identity: {{ aws_identity.stdout }}"

    - name: Get EKS token via AWS CLI
      shell: aws eks get-token --cluster-name sameer-cluster --region {{ aws_region }}
      register: eks_token
    - debug:
        msg: "EKS token JSON: {{ eks_token.stdout }}"

    - name: Delete old deployment (ignore errors if not present)
      shell: kubectl delete -f /home/ubuntu/Deployment.yml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
        AWS_REGION: "{{ aws_region }}"
      ignore_errors: yes

    - name: Delete old service (ignore errors if not present)
      shell: kubectl delete -f /home/ubuntu/Service.yml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
        AWS_REGION: "{{ aws_region }}"
      ignore_errors: yes

    - name: Apply Kubernetes deployment
      shell: kubectl apply -f /home/ubuntu/Deployment.yml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
        AWS_REGION: "{{ aws_region }}"

    - name: Apply Kubernetes service
      shell: kubectl apply -f /home/ubuntu/Service.yml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
        AWS_REGION: "{{ aws_region }}"
