kind: Service
apiVersion: v1
metadata:
  name: sameerskanade
  labels:
    app: sameerskanade
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
  selector:
    app: sameerskanade
  type: LoadBalancer